# #+OPTIONS: toc:nil

* Open And Accessible: A Critical Distinction				:toc:

* Introduction

In theory, the goal of both open access and accessibility is the same: making knowledge available to all rather than to a privileged few. In practice, however, open access and accessibility can function quite differently. This workshop will help you to evaluate platforms for their openness and accessibility, making for effective and broadly available pedagogy.

* What is accessibility?

Accessibility is the theory and practice of designing for people with disabilities. These can include mobility, sensory, cognitive, or other forms of disability. However, there are many approaches and best practices that can broadly help people both with and without disabilities. These approaches are collectively referred to as "universal design." As a teacher, thinking accessibly requires patience, empathy, and a certain amount of research, but the time and effort you put in can often help all of your students, not just those with disabilities.

* What is open access?

Open access means loosening restrictions on the use of works or giving works away for free. Thus, there are two general categories of open access:

- libre: exercising copyright to provide more freedoms to readers, consumers, or users
- gratis: giving materials away without cost

In scholarly publishing, there are two additional distinctions:

- Gold open access: an arrangement in which the publisher makes a work available on their own website or through their own distribution channels
- Green open access: an arrangement in which the author is allowed to host the work in a repository unrelated to the publisher, such as a university library

In general, the shared goal of these various approaches to open access is to make works more widely available.
 In practice, though, the specific approach employed can matter a great deal.

* Intersections

- Lifting economic or legal barriers to access often leaves cognitive, cultural, or social barriers in place that can have similar results. (For example, Wikipedia or the open source community.)
- Paradoxically, many "walled gardens," such as Apple and Facebook, are highly accessible while remaining steadfastly against open access.
- Libre open access can often be more useful in terms of accessibility, since it can allow works to be reformulated or republished in ways that are more accessible to certain populations.
- Open access can make accessibility possible, but doesn't mean something is automatically accessible. See the recent [[https://www.washingtonpost.com/local/education/why-uc-berkeley-is-restricting-access-to-thousands-of-online-lecture-videos/2017/03/15/074e382a-08c0-11e7-a15f-a58d4a988474_story.html][UC Berkley case]].

* Theory vs. Practice

There are many situations where accessibility or open access best practices have theoretically been followed, but which break with the spirit of openness and accessibility. For example, Blackboard is compliant with many accessibility best practices and can be used with screen readers, but many students find its interface cognitively inaccessible. Similarly, academia.edu allows for the "gratis" downloading of papers, but requires fees for many kinds of searches that would seem to violate the spirit of open access. Accessibility and open access shouldn't be thought of only in terms of compliance, checklists, and rules, but rather as a general approach or framework that can always be better applied with greater knowledge, empathy, and practical experience.

* Open or Accessible?

Are these general situations more in accordance with accessibility or open access? Both? Neither? Note that many of these may be ambiguous or dependent on individual circumstances.

- Class discussions on Blackboard
- Book on publisher's website in PDF form
- Physical copy of a book on library reserve
- Course texts on Dropbox
- An assignment in which students edit Wikipedia
- Course syllabus on WordPress site or GitHub
- Course lecture on YouTube
- Course lecture in person
- Printed handouts

* Tools and platforms

Which of these are accessible? Which of these are open?

- Blackboard
- WordPress
- Slack
- Twitter
- YouTube
- Wikipedia
- Facebook
- PDFs
- Amazon ebooks
- Microsoft Office
- Minecraft
- Project Gutenberg
- RSS
- GitHub
- Google Docs
- Internet Archive
- Dropbox

* How can I be more...

** Accessible

- Semantic design
- Multiple formats
- Use OCR
- Be flexible
- Research platforms

** Open

- Open web, not walled garden
- Contribute to communities
- Evangelize
- Use Creative Commons licenses
- Curate, remix, release

** Both

- Simple formats (plain text, HTML, SQL)
- Communicate with students
- Honesty, empathy, clear expression

* Resources

[[https://support.google.com/drive/topic/2650510?hl=en&ref_topic=2650510&visit_id=1-636298062499400622-1312580&rd=1][Google Drive Accessibility]]\\
[[http://accessibility.colostate.edu/blackboard.cfm][Blackboard Accessibility]]\\
[[http://www.ski.org/project/youdescribe][YouDescribe]]\\
[[https://www.theatlantic.com/technology/archive/2013/10/90-of-wikipedias-editors-are-male-heres-what-theyre-doing-about-it/280882/][Divirsity on Wikipedia]]\\
[[https://www.youtube.com/watch?v=W8_O3joo4aU][Blind Hackers]]\\
[[https://www.oercommons.org/][OER Commons]]\\
[[https://commons.gc.cuny.edu/][CUNY Academic Commons]]\\
